bindkey -e # Emacs

#
# Utility functions
#

# Source a file if it exists.
function __check_and_source {
    [[ -f "$1" ]] && source "$1"
}

#
# History
#

setopt HIST_EXPIRE_DUPS_FIRST # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS       # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS   # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS      # Do not display a previously found event.
setopt HIST_IGNORE_SPACE      # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS      # Do not write a duplicate event to the history file.

#
# Prompt
#

export PROMPT="%2~ %F{yellow}»%f "

#
# Aliases
#

__check_and_source "$ZDOTDIR/aliases.zsh"

#
# Completion
#

__check_and_source "$ZDOTDIR/completion.zsh"
